alias l='tree -L 2 --sort=mtime --dirsfirst -f -h --prune --du --noreport -up'
alias ll='ls -la'
alias ls='ls --color=auto'
alias qt='qutebrowser'
alias sdi='sudo dnf install'
alias sdu='sudo dnf update'
alias sv='sudo vim'
alias syno='synonym'
alias sys='systemctl'
alias v='vim'
alias vi='vim'
alias sudo="sudo "
