code --install-extension adpyke.vscode-sql-formatter
code --install-extension aliariff.auto-add-brackets
code --install-extension Asuka.insertnumbers
code --install-extension bastienboutonnet.vscode-dbt
code --install-extension bibhasdn.unique-lines
code --install-extension bradlc.vscode-tailwindcss
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension brunnerh.insert-unicode
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension chunsen.bracket-select
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension damonsk.vscode-wardley-maps
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension ElecTreeFrying.insert-random-text
code --install-extension esbenp.prettier-vscode
code --install-extension henriblancke.vscode-dbt-formatter
code --install-extension johnsoncodehk.volar
code --install-extension KevinRose.vsc-python-indent
code --install-extension leodevbro.blockman
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension ritwickdey.LiveServer
code --install-extension rlivings39.fzf-quick-open
code --install-extension samuelcolvin.jinjahtml
code --install-extension tushortz.python-extended-snippets
code --install-extension Tyriar.sort-lines
code --install-extension usernamehw.errorlens
code --install-extension znck.vue-language-features
